name: Build Doc
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          # microsoft repo in 18.04 is broken
          # sudo apt update -y
          sudo apt install -y libmpich-dev libgoogle-glog-dev libgflags-dev librdkafka-dev doxygen
      - name: Build Doc
        run: |
          mkdir build
          cd build
          cmake ..
          make doc
          cp ../misc/logo.png docs
      - name: Commit Doc
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git branch -D gh-pages || true
          git checkout --orphan gh-pages
          shopt -s extglob
          rm -rf !(build)
          rm -rf .github .clang-format .gitattributes .gitmodules .gitignore
          mv build/docs/* ./
          rm -rf build
          git add .
          git commit -m "auto build from ${{ github.sha }}."
          git push -f origin gh-pages

